name: Backend Lint & Format Check

on:
  workflow_dispatch:
  push:
    paths:
      - govtool/backend/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Use Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.1'
          cabal-version: '3.8.1.0'
          cabal-update: false

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Install HLint
        run: |
          rm -rf ~/.cabal ~/.ghcup
          mkdir -p ~/.cabal
          echo 'repository hackage.haskell.org' > ~/.cabal/config
          echo '  url: https://hackage.haskell.org/' >> ~/.cabal/config
          echo '  secure: True' >> ~/.cabal/config
          cabal update --index-state=HEAD
          cabal install hlint

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hlint
        run: pre-commit run --all-files hlint

  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Use Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.1'
          cabal-version: '3.8.1.0'
          cabal-update: false

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Install HLint
        run: |
          rm -rf ~/.cabal ~/.ghcup
          mkdir -p ~/.cabal
          echo 'repository hackage.haskell.org' > ~/.cabal/config
          echo '  url: https://hackage.haskell.org/' >> ~/.cabal/config
          echo '  secure: True' >> ~/.cabal/config
          cabal update --index-state=HEAD
          cabal install stylish-haskell

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hlint
        run: pre-commit run --all-files stylish-haskell
